---
apiVersion: v1
kind: Service
metadata:
  name: gazebo-client
spec:
  type: ClusterIP
  ports:
    - name: websocket
      port: 8080
      targetPort: 8080
    - name: webserver
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: gazebo-client
    group: robot-common-group
    robotType: simulated
