---
apiVersion: v1
kind: Service
metadata:
  name: zenoh-router
spec:
  type: ClusterIP
  ports:
    - name: zenoh-router
      port: 7447
      protocol: TCP
      targetPort: 7447
  selector:
    app: zenoh-router
    middlewareName: zenoh
---
apiVersion: v1
kind: Service
metadata:
  name: robots-gazebo
spec:
  type: ClusterIP
  ports:
    - name: gazebo
      port: 11345
      protocol: TCP
    - name: zenoh
      port: 7447
      protocol: TCP
  selector:
    app: gazebo-server
    group: robot-common-group
    robotType: simulated
---
apiVersion: v1
kind: Service
metadata:
  name: rviz
spec:
  type: ClusterIP
  ports:
    - name: zenoh
      port: 7447
      targetPort: 7447
      protocol: TCP
  selector:
    app: rviz
    group: robot-common-group
    robotType: simulated
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cyclone-dds-local-config
data:
  cyclone-dds-profiles.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <CycloneDDS
      xmlns="https://cdds.io/config"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd"
    >
      <Domain Id="any">
        <General>
          <Interfaces>
            <NetworkInterface
              autodetermine="false"
              priority="default"
              multicast="false"
              name="lo"
            />
          </Interfaces>
          <AllowMulticast>false</AllowMulticast>
        </General>
        <Discovery>
              <ParticipantIndex>auto</ParticipantIndex>
              <Peers>
                  <Peer Address="localhost"/>
              </Peers>
              <MaxAutoParticipantIndex>120</MaxAutoParticipantIndex>
          </Discovery>
        <Tracing>
          <Verbosity>config</Verbosity>
          <OutputFile>
          ${HOME}/.cdds.log.${CYCLONEDDS_PID}
        </OutputFile>
        </Tracing>
      </Domain>
    </CycloneDDS>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robots-common
data:

  # Ros domain id
  ros.domain.id: "40"

  # master uri
  gazebo.master.uri: http://robots-gazebo:11345

  # world
  gazebo.world: "opil_factory"

  # devel environment
  devel.environment: "true"

  # Use gpu for simulation
  use.gpu: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robot-1
data:
  description.file: dual_laser.urdf.xacro
  id: robot
  init.position.x: "2.0"
  init.position.y: "2.0"
  init.position.z: "0.1"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zenoh-router
  labels:
    app: zenoh-router
    middlewareName: zenoh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zenoh-router
      middlewareName: zenoh
  template:
    metadata:
      labels:
        app: zenoh-router
        middlewareName: zenoh
    spec:
      containers:
        - name: zenoh-router
          image: eclipse/zenoh:0.7.2-rc
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: debug
          args:
            - --no-multicast-scouting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robots-gazebo-server
  labels:
    app: gazebo-server
    group: robot-common-group
    robotType: simulated
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gazebo-server
      group: robot-common-group
      robotType: simulated
  replicas: 1
  template:
    metadata:
      labels:
        app: gazebo-server
        group: robot-common-group
        robotType: simulated
    spec:
      volumes:
        - name: shared-tmp
          emptyDir: {}
        - name: cyclone-dds-cfg
          configMap:
            name: cyclone-dds-local-config
      containers:
        - name: gzserver
          image: >-
            robotnik/robotnik-simulations:rb-theron-gazebo-humble-0.3.0-rc03
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-tmp
              mountPath: /tmp
            - name: cyclone-dds-cfg
              mountPath: /etc/cyclone-dds/cyclone-dds-profiles.xml
              subPath: cyclone-dds-profiles.xml
          env:
            - name: ROS_DOMAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: robots-common
                  key: ros.domain.id
            - name: WORLD_NAME
              valueFrom:
                configMapKeyRef:
                  name: robots-common
                  key: gazebo.world
            - name: DEVELOPMENT_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: robots-common
                  key: devel.environment
            # Fixed configuration
            - name: GUI
              value: "false"
            - name: ROS_BU_LAUNCH
              value: >
                gazebo.launch.py
                gui:=$GUI
                verbose:=true
                world_name:=$WORLD_NAME
                -d
            - name: HEALTHCHECK_NODES
              value: "/gazebo"
            - name: CYCLONEDDS_URI
              value: /etc/cyclone-dds/cyclone-dds-profiles.xml
          ports:
            - containerPort: 11345
              name: gazeboport
          resources:
            requests:
              cpu: 1200m
              memory: 500Mi
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - |
                    if [[ $DEVELOPMENT_ENVIRONMENT == "true" ]]
                    then
                      exit 0
                    fi
                    sudo apt -y purge \
                      wget \
                      curl \
                    sudo apt clean
                    sudo sed -i '/%robot ALL=(ALL) NOPASSWD:ALL/d' /etc/sudoers
                    exit 0

          startupProbe:
            exec:
              command:
                - ros_entrypoint.sh
                - ros_healthcheck.sh
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - ros_entrypoint.sh
                - ros_healthcheck.sh
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command:
                - ros_entrypoint.sh
                - ros_healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 30
            timeoutSeconds: 10
        - name: robot-1-spawner
          image: >-
            robotnik/robotnik-simulations:rb-theron-gazebo-humble-0.3.0-rc03
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-tmp
              mountPath: /tmp
            - name: cyclone-dds-cfg
              mountPath: /etc/cyclone-dds/cyclone-dds-profiles.xml
              subPath: cyclone-dds-profiles.xml
          env:
            - name: ROS_DOMAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: robots-common
                  key: ros.domain.id
            - name: DEVELOPMENT_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: robots-common
                  key: devel.environment
            - name: GPU
              valueFrom:
                configMapKeyRef:
                  name: robots-common
                  key: use.gpu
            - name: ROBOT_ID
              valueFrom:
                configMapKeyRef:
                  name: robot-1
                  key: id
            - name: ROBOT_DESCRIPTION_FILE
              valueFrom:
                configMapKeyRef:
                  name: robot-1
                  key: description.file
            - name: POS_X
              valueFrom:
                configMapKeyRef:
                  name: robot-1
                  key: init.position.x
            - name: POS_Y
              valueFrom:
                configMapKeyRef:
                  name: robot-1
                  key: init.position.y
            - name: POS_Z
              valueFrom:
                configMapKeyRef:
                  name: robot-1
                  key: init.position.z
            # Fixed configuration
            - name: CHECK_NODES
              value: "true"
            - name: NODES_TO_CHECK
              value: "/gazebo"
            - name: HEALTHCHECK_NODES
              value: >
                /${ROBOT_ID}/controller_manager
                /${ROBOT_ID}/front_laser
                /${ROBOT_ID}/imu
                /${ROBOT_ID}/rear_laser
                /${ROBOT_ID}/robot_state_publisher
                /${ROBOT_ID}/robotnik_base_control
                /${ROBOT_ID}/ros_control
            - name: ROS_BU_LAUNCH
              value: >
                spawn.launch.py
            - name: CYCLONEDDS_URI
              value: /etc/cyclone-dds/cyclone-dds-profiles.xml
          resources:
            requests:
              cpu: 300m
              memory: 150Mi
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - |
                    if [[ $DEVELOPMENT_ENVIRONMENT == "true" ]]
                    then
                      exit 0
                    fi
                    sudo apt -y purge \
                      wget \
                      curl \
                    sudo apt clean
                    sudo sed -i '/%robot ALL=(ALL) NOPASSWD:ALL/d' /etc/sudoers
                    exit 0

          startupProbe:
            exec:
              command:
                - ros_entrypoint.sh
                - ros_healthcheck.sh
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - ros_entrypoint.sh
                - ros_healthcheck.sh
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command:
                - ros_entrypoint.sh
                - ros_healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 30
            timeoutSeconds: 10
        - name: zenoh-bridge
          image: >-
            robotnik/zenoh-dds-bridge:humble-0.7.2-rc-1
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-tmp
              mountPath: /tmp
            - name: cyclone-dds-cfg
              mountPath: /etc/cyclone-dds/cyclone-dds-profiles.xml
              subPath: cyclone-dds-profiles.xml
          env:
            - name: ROS_DOMAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: robots-common
                  key: ros.domain.id
            - name: CYCLONEDDS_URI
              value: /etc/cyclone-dds/cyclone-dds-profiles.xml
            - name: ZENOH_MULTICAST_SCOUTING
              value: "false"
            - name: ZENOH_FORWARD_DISCOVERY
              value: "false"

            - name: ZENOH_LISTENERS
              value: >-
                tcp/0.0.0.0:7447
                tcp/zenoh-router:7447
            - name: ZENOH_ENDPOINTS
              value: >-
                tcp/zenoh-router:7447
            - name: RUST_LOG
              value: debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rviz
  labels:
    app: rviz
    group: robot-common-group
    robotType: simulated
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rviz
      group: robot-common-group
      robotType: simulated
  replicas: 1
  template:
    metadata:
      labels:
        app: rviz
        group: robot-common-group
        robotType: simulated
    spec:
      volumes:
        - name: data
          emptyDir: {}
        - name: cyclone-dds-cfg
          configMap:
            name: cyclone-dds-local-config
      containers:
        - name: rviz
          image: >-
            robotnik/robotnik-simulations:rb-theron-gazebo-humble-0.3.0-rc03
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /home/robot/data
            - name: cyclone-dds-cfg
              mountPath: /etc/cyclone-dds/cyclone-dds-profiles.xml
              subPath: cyclone-dds-profiles.xml
          env:
            - name: ROS_DOMAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: robots-common
                  key: ros.domain.id
            - name: DEVELOPMENT_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: robots-common
                  key: devel.environment
            # Fixed configuration
            - name: STARTUP_TYPE
              value: graphical
            - name: GUI_ZENITY_TEXT
              value: "Launch RViz?"
            - name: RVIZ_CFG_FILE
              value: /home/robot/config/rb-theron.rviz
            - name: GUI_COMMAND
              value: "rviz2 -d ${RVIZ_CFG_FILE} --ros-args --remap use_sim_time:=true"
            - name: CYCLONEDDS_URI
              value: /etc/cyclone-dds/cyclone-dds-profiles.xml
          ports:
            - containerPort: 5900
              name: vnc
          resources:
            requests:
              cpu: 1800m
              memory: 600Mi
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - |
                    if [[ $DEVELOPMENT_ENVIRONMENT == "true" ]]
                    then
                      exit 0
                    fi
                    sudo apt -y purge \
                      wget \
                      curl \
                    sudo apt clean
                    sudo sed -i '/%robot ALL=(ALL) NOPASSWD:ALL/d' /etc/sudoers
                    exit 0
          startupProbe:
            tcpSocket:
              port: vnc
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: vnc
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
            timeoutSeconds: 10
          livenessProbe:
            tcpSocket:
              port: vnc
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 30
            timeoutSeconds: 10

        - name: zenoh-bridge
          image: >-
            robotnik/zenoh-dds-bridge:humble-0.7.2-rc-1
          imagePullPolicy: Always
          volumeMounts:
            - name: cyclone-dds-cfg
              mountPath: /etc/cyclone-dds/cyclone-dds-profiles.xml
              subPath: cyclone-dds-profiles.xml
          env:
            - name: ROS_DOMAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: robots-common
                  key: ros.domain.id
            - name: CYCLONEDDS_URI
              value: /etc/cyclone-dds/cyclone-dds-profiles.xml
            - name: ZENOH_MULTICAST_SCOUTING
              value: "false"
            - name: ZENOH_FORWARD_DISCOVERY
              value: "false"
            - name: ZENOH_LISTENERS
              value: >-
                 tcp/0.0.0.0:7447
                 tcp/robots-gazebo:7447
                 tcp/zenoh-router:7447
            #   # tcp/rviz:7447
            #   # tcp/robots-gazebo:7447
            #   # tcp/rviz:7447
            - name: ZENOH_ENDPOINTS
              value: >-
                tcp/zenoh-router:7447
              # tcp/rviz:7447
              # tcp/robots-gazebo:7447
            - name: RUST_LOG
              value: debug
